# Generated by Django 5.2.11 on 2026-02-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastUpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('user', 'User')], max_length=255),
        ),
    ]
